version: "3"

services:
  stock_example:
    container_name: stock_example
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: stock_example
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: stock_example
      MYSQL_PASSWORD: stock_example
      TZ: 'Asia/Seoul'
    restart: always
    ports:
      - "3306:3306"
    command:
       - "mysqld"
       - "--character-set-server=utf8mb4"
       - "--collation-server=utf8mb4_unicode_ci"
  redis:
    image: redis:alpine
    command: redis-server --port 6379
    container_name: redis_boot
    hostname: redis_boot
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - "6379:6379"